autoencoder:
  checkpoint: lightning_logs/version_4/checkpoints/epoch=2182-step=10914.ckpt
  decoder_dimensions:
  - 128
  - 256
  - 256
  - 3
  encoder_dimensions:
  - 3
  - 64
  - 128
  - 256
  - 128
dataset: shapenet
ddpg:
  batch_size_actor: 100
  max_action: 2
  max_steps: 1000000
  regularization: 0.1
  start_time: 1000
  w_chamfer: 5.0
  w_disc: 0.1
  w_gfv: 0.1
gan:
  batch_size: 8
  checkpoint: /home/zacharie/rl_gan/rl-gan-net/lightning_logs/version_13/checkpoints/epoch=53-step=539.ckpt
  critic_dimensions:
  - 128
  - 128
  - 128
  - 1
  generator_dimensions:
  - 32
  - 128
  - 256
  - 256
  - 128
  max_epochs: 10000
gfv_dim: 128
num_points: 2048
split: 1
z_dim: 32
