gfv_dim: 128
z_dim: 32
num_points: 2048
split: 1
batch_size: 8
autoencoder:
  encoder_dimensions: [3, 64, 128, 256, 128]
  decoder_dimensions: [128, 256, 256, 3]
  checkpoint: "lightning_logs/version_4/checkpoints/epoch=2182-step=10914.ckpt"
gan:
  generator_dimensions: [32, 128, 256, 256, 128]
  critic_dimensions: [128, 128, 128, 1]
  checkpoint: "lightning_logs/version_12/checkpoints/epoch=393-step=3939.ckpt"
ddpg:
  max_action: 2
  max_steps: 1.0e+6
  start_time: 1.0e+3
  batch_size_actor: 100
  w_gfv: 0.1
  w_chamfer: 5.0
  w_disc: 0.1
  regularization: 0.1